name: CI/CD

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'examples/**'

env:
  CGO_ENABLED: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Install Dependencies
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/mgechev/revive@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Go Format Check
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Code not formatted:"
          gofmt -l .
          exit 1
        fi

    - name: Go Vet
      run: go vet $(go list ./... | grep -v '/examples/')

    - name: Staticcheck
      run: staticcheck $(go list ./... | grep -v '/examples/')

    - name: Revive (Golint replacement)
      run: revive $(go list ./... | grep -v '/examples/') || true

    - name: Security Scan (gosec)
      continue-on-error: true
      run: |
        echo "Running security scan..."
        gosec $(go list ./... | grep -v '/examples/') || true
        echo "✅ Security scan completed"

    - name: Test with Race Detection
      run: go test -race -timeout 5m -v $(go list ./... | grep -v '/examples/')

    - name: Test Coverage
      run: |
        go test -coverprofile=coverage.out $(go list ./... | grep -v '/examples/')
        go tool cover -func=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
        disable_search: false

  build:
    name: Build Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.25']
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Build
      run: go build -v $(go list ./... | grep -v '/examples/')

    - name: Short Test (no race, faster)
      run: go test -short -timeout 30s $(go list ./... | grep -v '/examples/')
