name: PR Quick Check

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'examples/**'

env:
  CGO_ENABLED: 1

jobs:
  quick-test:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Quick Quality Check
      run: |
        # Format check
        test -z "$(gofmt -l . | grep -v '^examples/')"
        
        # Vet
        go vet $(go list ./... | grep -v '/examples/')
        
        # Basic test
        go test -short $(go list ./... | grep -v '/examples/')

    - name: Install Security Tools
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Security Scan
      run: gosec --exclude=G104,G306,G301 $(go list ./... | grep -v '/examples/')